//This file is not autogenerated, please edit according to your needs by commenting out/in or editing settings

//Config file location from home:
#define CONFFILE		".config/cwm/cwmrc"

//undefine this if you don't want an autoexec file to be executed.
#define AUTOEXEC

//set this to the shell you would like to execute the autoexec file with.
//Usually you want it to be /bin/sh.
//AUTOEXEC depends on this value.
#define SHBINDIR		"/bin/sh"

//set this to the path to your autoexec file
//AUTOEXEC depends on this value.
#define AUTOEXECDIR		"~/.config/cwm/autoexec"

//set this to specify the multiplier that the resize-big functions should resize with
#define CWM_FACTOR		10

//set this to specify the multiplier that the grow/shrink functions should resize with.
//This value applies to both sides.
#define CWM_FACTOR_KEEPAR	5
